-- AlterTable
ALTER TABLE `paciente` ADD COLUMN `abo` VARCHAR(5) NULL,
    ADD COLUMN `bairro` VARCHAR(100) NULL,
    ADD COLUMN `celular_i` VARCHAR(20) NULL,
    ADD COLUMN `celular_ii` VARCHAR(20) NULL,
    ADD COLUMN `cep` VARCHAR(12) NULL,
    ADD COLUMN `cidade` VARCHAR(100) NULL,
    ADD COLUMN `cns` VARCHAR(20) NULL,
    ADD COLUMN `dt_cadastro` DATETIME NULL,
    ADD COLUMN `email` VARCHAR(100) NULL,
    ADD COLUMN `nacionalidade` VARCHAR(90) NULL,
    ADD COLUMN `naturalidade` VARCHAR(90) NULL,
    ADD COLUMN `nm_mae` VARCHAR(150) NULL,
    ADD COLUMN `nm_pai` VARCHAR(150) NULL,
    ADD COLUMN `numero` VARCHAR(10) NULL,
    ADD COLUMN `qual_alergia` VARCHAR(70) NULL,
    ADD COLUMN `raca` ENUM('P', 'O', 'B', 'A', 'I', 'N') NULL,
    ADD COLUMN `rg_num` VARCHAR(25) NULL,
    ADD COLUMN `rg_org` VARCHAR(45) NULL,
    ADD COLUMN `tem_alergia` VARCHAR(3) NULL,
    ADD COLUMN `uf` CHAR(2) NULL;
