name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Pull and Deploy on VPS
    runs-on: ubuntu-latest

    steps:
      - name: Acessar VPS e fazer deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_URL }}
          username: ${{ secrets.FRONTEND_UBUNTU_USER }}
          key: ${{ secrets.VPS_SSH }}
          script: |
            # Navegar até o diretório onde o site está hospedado
            cd /home/application-well-siahme/htdocs/

            # Verificar se a pasta hemoseSystem existe, e fazer pull ou clone
            if [ -d "hemoseSystem" ]; then
              echo "hemoseSystem já existe. Fazendo git pull com rebase..."
              cd hemoseSystem
              git reset --hard HEAD         # Garante que não há mudanças locais
              git clean -fd                 # Remove arquivos não versionados
              git pull --rebase origin main # Rebase evita merges desnecessários
            else
              echo "hemoseSystem não existe. Fazendo git clone..."
              git clone https://github.com/Squad2-R-IV/hemoseSystem.git
              cd hemoseSystem
            fi

            # Entrar no diretório do frontend
            cd front

            # Carregar o NVM e definir a versão do Node.js
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22.15.0

            # Instalar dependências e gerar o build
            npm install
            npm run build

            # Copiar os arquivos do build para o diretório do site
            rm -rf /home/application-well-siahme/htdocs/siahme.application-well.com.br/*
            cp -r build/client/* /home/application-well-siahme/htdocs/siahme.application-well.com.br/
